### ISSUE TITLE
remove logic của view ra khỏi repository

### ISSUE THREAD

**Issue by nguyenngocanh94** [CaoVu-HP/Mongodb#2]
public function delete($param,$connect)
    {
        echo "Ban co chac chan muon xoa khong?? \n";
        echo "(Y Or N) ??";
        $input = fgetc(fopen('php://stdin', 'r'));
        if ($input == 'y') {
            $results = $connect->deleteMany(
                [
                    'code' => $param,
                ]);
            return $results->getDeletedCount();
        }
        if ($input == 'y') {
            echo "ket thuc \n";
            die();
        }
    }

**Comment by CaoVu-HP** [comment]
e đã remove logic ra khỏi repository:

    public function delete($param,$connect)
    {
        $results = $connect->deleteMany(
            [
                'code' => $param,
            ]);
        return $results->getDeletedCount();
    }
