### ISSUE TITLE
Index.php -> index

### ISSUE THREAD

**Issue by nguyenngocanh94** [CaoVu-HP/Mongodb#3]
kiểm tra và viết lại cho anh ra đây các code convention của php

**Comment by CaoVu-HP** [comment]
Quy tắc đặt tên :
(camelCase) ký tự đầu tiên của từ đầu tiên viết thường những ký tự đầu tiên của những từ tiếp theo được viết hoa --> áp dụng cho: tên biến, tên hàm
(PascalCase) cú pháp Pascal viết hoa chữ cái đầu tiên của mỗi từ --> áp dụng cho: tên lớp

Quy tắc xuống dòng:
Nếu có dấu phẩy thì xuống hàng sau dấu phẩy
Nếu có nhiều cấp lồng nhau, thì xuống hàng theo từng cấp
Dòng xuống hàng mới thì nên bắt đầu ở cùng cột với đoạn lệnh cùng cấp ở trên.

Tuân theo các chuẩn  PSR-1->PSR-2->PSR-4( Từ  tháng 10/2014 PSR-0 đã được đề xuất không sử dụng nữa và PSR-4 được đề xuất thay thế )

Ngoài ra còn một số các quy tắc khác, không được quy định cụ thể trong các bộ PSR.
Sử dụng phiên bản PHP mới nhất nếu có thể.
Khi khai báo mảng, các phần tử của mảng có thể được tách thành nhiều dòng. Khi làm vậy thì cần phải tuân thủ các quy tắc sau:
Phần từ đầu tiên của mảng phải được đặt trên một dòng mới.
Mỗi dòng chỉ được phép có một phần tử, các phần tử được indent một lần.
Cần phải có dấu phẩy ở cuối phần tử cuối cùng.
Dấu kết thúc khai báo mảng (ngoặc vuông) phải được đặt trên một dòng mới.
Với phiên bản PHP >= 5.4, hãy sử dụng [ ] để khai báo array, thay vì dùng array().
Tên biến được viết dưới dạng camelCase. Đối với tên property bên trong Model thì có thể viết dưới dạng snake_case cho phù hợp với tên của các cột trong các bảng của Database.
Sử dụng dấu ' đối với một string bình thường. Chỉ dùng " khi bên trong có khai triển biến PHP.
Cần có 1 space trước và sau các toán tử như +, -, , /, ., >, <, ==
