### ISSUE TITLE
Connect.php vẫn đang ở dạng code tuần tự -> chuyển về OOP

### ISSUE THREAD

**Issue by nguyenngocanh94** [CaoVu-HP/Mongodb#5]
use MongoDB\Client;
error_reporting(0);
//require autoload
require_once "vendor/autoload.php";
// khoi tao class Client
$conn = new Client("mongodb://127.0.0.1:27017");
//select database
$db = $conn->mongo;
//selection collection
$post = $db->users;
return $post;

**Comment by CaoVu-HP** [comment]
vâng e đã sửa theo OOP

<?php
namespace Cn;
use MongoDB\Client;

class Connect
{
    public function connect()
    {
        $conn = new Client("mongodb://127.0.0.1:27017");
//select database
        $db = $conn->mongo;
//selection collection
        return $db->users;
    }
}

?>
